---
- name: add users to docker group
  block:
  - name: check if docker service exists
    stat: path=/etc/init.d/docker
    register: docker_service_status
    ignore_errors: true

  - name: add users to docker group
    user:
      name: "{{ item }}"
      group: docker
      append: true
    with_items: "{{ os_docker_users }}"
    when:
    - docker_service_status.stat.exists | default(false)
  become: true
