---
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
# Condition required when you test the role in a container environment.
  when: ansible_virtualization_type != 'containerd' or ansible_virtualization_type != 'container' or ansible_virtualization_type != 'docker'
